spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tago?useSSL=false&serverTimezone=UTC
    username: root
    password: dlgksmf4051
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret-key: ${JWT_SECRET_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
