spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tago?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

jwt:
  secret-key: ${JWT_SECRET_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
