spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 11
  sql:
    init:
      mode: never

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: false

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  tomcat:
    connection-timeout: 300s
    keep-alive-timeout: 300s

jwt:
  secretKey: ${JWT_SECRET_KEY}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

slack:
  bot-token: ${SLACK_BOT_TOKEN}
  postMessageUrl : "https://slack.com/api/chat.postMessage"
  channel:
    monitor: "#불편신고"

ncloud:
  credentials:
    access-key: ${NCLOUD_ACCESS_KEY}
    secret-key: ${NCLOUD_SECRET_KEY}
  sms:
    base-url: ${NCLOUD_SMS_BASE_URL}
    service-id: ${NCLOUD_SMS_SERVICE_ID}
    calling-number: ${NCLOUD_SMS_CALLING_NUMBER}

fcm:
  certification-path: ${FCM_CERTIFICATION_PATH}