version: '3.7'

services:
  redis:
    image: redis:latest
    command: redis-server
    container_name: tago-redis
    ports:
      - "6379:6379"
  spring:
    build:
      context: ../
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - "8080:8080"
    container_name: tago-spring
    environment:
      DATABASE_URL: 'jdbc:mysql://tago.cjn3xrjw75zo.ap-northeast-2.rds.amazonaws.com:3306/tago?serverTimezone=Asia/Seoul'
      DATABASE_USERNAME: 'admin'
      DATABASE_PASSWORD: 'tagotago!!'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      KAKAO_CLIENT_ID: 'bf9b0d47a797d8efdd9ba087afaf9d5f'
      JWT_SECRET_KEY: 'Z29nby10bS1zZXJ2ZXItZGxyamVvYW9yb3JodG9kZ290c3Atam9vbmdhbmduaW0teWVvbHNpbWhpaGFsZ2VveW8K'
      SLACK_BOT_TOKEN: 'xoxb-5520745773186-5840693042758-icCCUW416rFnThEZEc8rr9NH'
      NCLOUD_ACCESS_KEY: 'Sq4USvwaGUiBH0uPFxL3'
      NCLOUD_SECRET_KEY: 'aqRF8fkoSRFnKRsKcn3KSNv12WVelv1wE9vzb5FN'
      NCLOUD_SMS_BASE_URL: 'https://sens.apigw.ntruss.com/sms/v2/services/ncp:sms:kr:315618795007:tago'
      NCLOUD_SMS_CALLING_NUMBER: '01098652532'
      NCLOUD_SMS_SERVICE_ID: 'ncp:sms:kr:315618795007:tago'